Javascript is added
Boby900/calculator-js pull request #4
Opened 2023-01-22 11:45 UTC by srujith-reddy

I think there is no problem with the javascript you wrote. It's just insufficient.
I have added the code that is required for the proper functioning of the app . 
you can modify the design now.

2023-01-23 06:14 UTC, Boby900 commented on index.js
> +mulitply.addEventListener('click',function(){
thanks @srujith-reddy , but mistakenly you wrote the incorrected spelling of multipy, which is making the  code buggy

2023-01-23 06:18 UTC, Boby900 requested changes

2023-01-23 06:18 UTC, Boby900 commented on index.js
> +mulitply.addEventListener('click',function(){
thanks @srujith-reddy , but mistakenly you wrote the incorrected spelling of multiply, which is making the code buggy

2023-01-23 06:18 UTC, srujith-reddy commented
Oh, I am sorry , I didn't test that thing , I tested addition and
subtraction , I will change multiplication as well.

On Mon, 23 Jan 2023, 11:44 Boby Tiwari, ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In index.js
> <https://github.com/Boby900/calculator-js/pull/4#discussion_r1083677626>:
>
> > +    result_window.innerHTML=ans;
> +
> +})
> +
> +
> +substraction.addEventListener('click',function(){
> +    let x=type_convert(firstNum.value);
> +    let y=type_convert(secondNum.value);
> +    let ans=x-y;
> +    console.log(ans);
> +    result_window.innerHTML=ans;
> +
> +})
> +
> +
> +mulitply.addEventListener('click',function(){
>
> thanks @srujith-reddy <https://github.com/srujith-reddy> , but mistakenly
> you wrote the incorrected spelling of multipy, which is making the code
> buggy
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Boby900/calculator-js/pull/4#pullrequestreview-1265047184>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWL3L3HUYEDSDZFZMJZMOPDWTYOU7ANCNFSM6AAAAAAUC6AU4M>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-01-24 02:03 UTC, Boby900 approved these changes
thanks @srujith-reddy  for making my calculator up and running

2023-01-24 02:04 UTC, merged